title: chengbilly92's blog
description: >- # this means to ignore newlines until "baseurl:"
  A personal blog for recording various insights and notes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  chengbilly92

# Build settings
theme: minima
plugins:
  - jekyll-feed
